# Generated by matugen (via DMS user templates) → fish/conf.d/nocturne-colors.fish
# Fish syntax colors tracking the wallpaper palette. (dank16 = ANSI-ordered.)
set -g fish_color_normal        {{dank16.color7.default.hex_stripped}}
set -g fish_color_command       {{colors.primary.default.hex_stripped}}
set -g fish_color_keyword       {{colors.tertiary.default.hex_stripped}}
set -g fish_color_quote         {{dank16.color2.default.hex_stripped}}
set -g fish_color_redirection   {{dank16.color6.default.hex_stripped}}
set -g fish_color_end           {{colors.primary.default.hex_stripped}}
set -g fish_color_error         {{dank16.color1.default.hex_stripped}}
set -g fish_color_param         {{dank16.color7.default.hex_stripped}}
set -g fish_color_comment       {{colors.outline.default.hex_stripped}}
set -g fish_color_operator      {{dank16.color6.default.hex_stripped}}
set -g fish_color_escape        {{colors.tertiary.default.hex_stripped}}
set -g fish_color_autosuggestion {{colors.outline.default.hex_stripped}}
set -g fish_color_cwd           {{dank16.color2.default.hex_stripped}}
set -g fish_color_cwd_root      {{dank16.color1.default.hex_stripped}}
set -g fish_color_user          {{colors.primary.default.hex_stripped}}
set -g fish_color_host          {{colors.tertiary.default.hex_stripped}}
set -g fish_color_host_remote   {{dank16.color3.default.hex_stripped}}
set -g fish_color_selection --background={{colors.surface_container_high.default.hex_stripped}}
set -g fish_color_search_match --background={{colors.surface_container_high.default.hex_stripped}}
# Pager (completion menu)
set -g fish_pager_color_prefix      {{colors.primary.default.hex_stripped}}
set -g fish_pager_color_completion  {{dank16.color7.default.hex_stripped}}
set -g fish_pager_color_description {{colors.outline.default.hex_stripped}}
set -g fish_pager_color_selected_background --background={{colors.surface_container_high.default.hex_stripped}}
