-- Generated by matugen (via DMS user templates) → ~/.config/hypr/colors.lua
-- Preserves David's signature two-stop gradient border, but sourced from the
-- wallpaper palette instead of the hard-coded cyan→mint.
return {
  -- 45° gradient: primary → tertiary (the two most vivid Material roles)
  active = { "rgba({{colors.primary.default.hex_stripped}}ee)", "rgba({{colors.tertiary.default.hex_stripped}}ee)" },
  inactive = "rgba({{colors.outline.default.hex_stripped}}aa)",
  -- Extra roles, exposed in case other parts of the Lua config want them.
  primary   = "{{colors.primary.default.hex}}",
  secondary = "{{colors.secondary.default.hex}}",
  tertiary  = "{{colors.tertiary.default.hex}}",
  surface   = "{{colors.surface.default.hex}}",
  on_surface = "{{colors.on_surface.default.hex}}",
  error     = "{{colors.error.default.hex}}",
}
