-- Generated by matugen (via DMS user templates) → nvim/lua/nocturne/generated.lua
-- A proper base16 palette consumed by lua/nocturne/palette.lua (mini.base16).
--
-- base00–07 are a dark→light ramp taken from Material *surface* roles; base08–0F
-- are the accent hues taken from the ANSI dank16 slots. (dank16.colorN is ANSI
-- ordered — color1=red, color2=green, … — NOT base16 ordered, so we remap.)
return {
  base00 = "{{colors.surface.default.hex}}",                 -- default background (darkest)
  base01 = "{{colors.surface_container_low.default.hex}}",   -- lighter bg (statusline, cursorline)
  base02 = "{{colors.surface_container_high.default.hex}}",  -- selection background
  base03 = "{{colors.outline.default.hex}}",                 -- comments, line numbers
  base04 = "{{colors.on_surface_variant.default.hex}}",      -- dark foreground
  base05 = "{{colors.on_surface.default.hex}}",              -- default foreground
  base06 = "{{dank16.color7.default.hex}}",                  -- light foreground
  base07 = "{{dank16.color15.default.hex}}",                 -- lightest foreground
  -- Accents: the must-be-readable ones (functions/keywords/support/errors) come
  -- from Material *roles*, which are always contrast-tuned for the dark surface
  -- (a raw ANSI slot can render near-black on a low-saturation wallpaper). Only
  -- strings/numbers use the bright ANSI variants, which stay light.
  base08 = "{{colors.error.default.hex}}",                   -- red      — variables, errors
  base09 = "{{dank16.color11.default.hex}}",                 -- yellow   — numbers, constants
  base0A = "{{dank16.color3.default.hex}}",                  -- yellow   — classes, search
  base0B = "{{dank16.color10.default.hex}}",                 -- green    — strings
  base0C = "{{colors.secondary.default.hex}}",               -- support, regex
  base0D = "{{colors.primary.default.hex}}",                 -- functions
  base0E = "{{colors.tertiary.default.hex}}",                -- keywords
  base0F = "{{dank16.color9.default.hex}}",                  -- deprecated
}
