-- ╭──────────────────────────────────────────────────────────╮
-- │  Nocturne — custom Neovim                                  │
-- │  Structure:                                                │
-- │    lua/config/*   → options, keymaps, autocmds, lazy       │
-- │    lua/plugins/*  → one spec file per concern              │
-- │    lua/nocturne/* → palette (regenerated by matugen)       │
-- ╰──────────────────────────────────────────────────────────╯

vim.g.mapleader = " "
vim.g.maplocalleader = " "
vim.g.have_nerd_font = true

require("config.options")
require("config.keymaps")
require("config.autocmds")
require("config.lazy")
