#? Nocturne btop config
color_theme = "nocturne"
theme_background = False
truecolor = True
force_tty = False
vim_keys = True
rounded_corners = True
graph_symbol = "braille"
shown_boxes = "cpu mem net proc"
update_ms = 1000
proc_sorting = "cpu lazy"
proc_tree = False
proc_gradient = True
proc_per_core = False
cpu_graph_upper = "total"
show_gpu_info = "On"
show_uptime = True
show_battery = False
clock_format = "%H:%M"
